### LISTAR LOS PUNTOS DE CLASE
GET http://localhost:5000/inspuntclas/S/40/37 HTTP/1.1
Authorization: banner eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY2MzY0Mzk2OH0.1LAb0CB-scWLhvfZlVOA7Q_rh4W2Ih9zR5GRmA_pPhY

### ELIMINAR LOS PUNTOS DE CLASE
DELETE http://localhost:5000/pointcl/1 HTTP/1.1

### INSERTAR LOS PUNTOS DE CLASE
POST http://localhost:5001/inspuntclas/ HTTP/1.1 
Content-Type: application/json
Authorization: banner eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY2MzY0Mzk2OH0.1LAb0CB-scWLhvfZlVOA7Q_rh4W2Ih9zR5GRmA_pPhY

{
    "id_inscrip" : 43,
    "id_tipopunt" : 35,
    "id_sesion" : 45
}

### VALIDAR SI YA SE LE INSERTO ESA CANTIDAD DE PUNTOS EN UNA SECION
POST http://localhost:5000/inspuntclas/valit HTTP/1.1 
Content-Type: application/json
Authorization: banner eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY2MzY0Mzk2OH0.1LAb0CB-scWLhvfZlVOA7Q_rh4W2Ih9zR5GRmA_pPhY

{
    "id_inscrip" : 33,
    "id_tipopunt" : 10,
    "id_sesion" : 31
}

### ELIMINAR UN ALUMNO EN UN PUNTO DE CLASE DE UNA SESION 
POST http://localhost:5000/inspuntclas/delet HTTP/1.1 
Content-Type: application/json
Authorization: banner eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY2MzY0Mzk2OH0.1LAb0CB-scWLhvfZlVOA7Q_rh4W2Ih9zR5GRmA_pPhY

{
    "id_inscrip" : 37,
    "id_tipopunt" : 12,
    "id_sesion" : 40
}