### LISTAR LOS CONTENIDOS POR SESSION
GET http://localhost:5000/contses/10 HTTP/1.1

### ELIMINAR UN CONTENIDO DE UNA SESSION
DELETE http://localhost:5000/contses/14 HTTP/1.1

### INSERTAR UN CONTENIDO DE UNA SESSION
POST http://localhost:5000/contses/ HTTP/1.1 
Content-Type: application/json

{
    "idsession" : 10,
    "idtipocont" : 2,
    "name": "Contenido de seccion",
    "descr": "hajdhajkdhas asdasdhsajkdhas jashdjkashdjaskdhsa jashdjkashdjksa haskjdhaskjdhas",
    "urlcont": "http://hjasdhkasd.com"
}

### ACTUALIZAR UN CONTENIDO DE UNA SESSION
PUT http://localhost:5000/contses/4 HTTP/1.1 
Content-Type: application/json

{
    "idtipocont" : 3,
    "name": "Contenido de seccion",
    "descr": "El contenido generico de pruebas",
    "urlcont": "http://hjasdhkasd.com"
}