### LISTAR LOS ADMINISTRADORES
GET http://localhost:5001/api2/admi/%20 HTTP/1.1
Authorization: banner eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY2MzY0Mzk2OH0.1LAb0CB-scWLhvfZlVOA7Q_rh4W2Ih9zR5GRmA_pPhY

### LEER UN USUARIOS ADMINISTRADOR
GET http://localhost:5001/admi/read/1 HTTP/1.1

### ELIMINAR UN ADMINISTRADOR
DELETE http://localhost:5000/admi/1 HTTP/1.1

### INSERTAR UN ADMINISTRADOR
POST http://localhost:5000/admi/ HTTP/1.1 
Content-Type: application/json

{
    "name" : "Andrea graciela",
    "telf" :  969280255,
    "correo" : "arturo1421sdfFGsdf2000@gmail.com",
    "pass" : "Ca14654578",
    "tipoadm": "Trabajador",
    "photo": "http://jkjasjdaksdjaslkdjsa"
}

### ACTUALIZAR UN ADMINISTRADOR
PUT http://localhost:5000/admi/7 HTTP/1.1 
Content-Type: application/json

{
    "name" : "Andrea graciela",
    "telf" : 985796307,
    "correo" : "arturo20250@gmail.com",
    "pass" : "Ca14654578",
    "tipoadm": "Administrador",
    "photo": "ajkdajldkajsdklasjdlaskjdk"
}