### LISTA A TODOS LOS CICLOS CON SUS RESPECTIVAS ANALITICAS
GET http://localhost:5000/anli/cicl/sincrono/15 HTTP/1.1
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY0NzY2OTY0M30.E6MQy_q72P3FajQMLBPvO88jtPQo2N6XWA7rBR-HNR4

### LISTA A TODOS LOS CICLOS CON SUS RESPECTIVAS ANALITICAS
GET http://localhost:5001/api/anli/cicl/sincrono/puntos/29 HTTP/1.1
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY0NzY2OTY0M30.E6MQy_q72P3FajQMLBPvO88jtPQo2N6XWA7rBR-HNR4