### LIST UN USUARIOS  CLIENTE ANALISTA
GET http://localhost:5001/api/v1/clientAnalit/ HTTP/1.1

### LEER UN USUARIOS  CLIENTE ANALISTA
GET http://localhost:5001/api/v1/clientAnalit/read/2 HTTP/1.1

### INSERTAR UN CLIENTE ANALISTA
POST http://localhost:5001/api/v1/clientAnalit/ HTTP/1.1 
Content-Type: application/json

{
    "nombre" : "Carlos Arturo",
    "apellidos": "Guerrero Castillo",
    "telf" :  "969280255",
    "correo" : "pedrna122@gmail.com",
    "pass" : "Ca14654578",
    "photo": "https://nyrevconnect.com/wp-content/uploads/2017/06/Placeholder_staff_photo-e1505825573317.png"
}

### ACTUALIZAR UN  CLIENTE ANALISTA
PUT http://localhost:5001/api/v1/clientAnalit/2 HTTP/1.1 
Content-Type: application/json

{
    "nombre" : "Pedro Rodrigues",
    "apellidos": "Guevara Castillo",
    "telf" :  "985796307",
    "photo": "https://nyrevconnect.com/wp-content/uploads/2017/06/Placeholder_staff_photo-e1505825573317.png"
}

### ACTUALIZAR LA INFORMACION DE LA SELCION DEL CLIENTE ANALISTA
PUT http://localhost:5001/api/v1/clientAnalit/infoCuenta/2 HTTP/1.1 
Content-Type: application/json

{
    "correo" : "pedrna155@gmail.com",
    "pass" : "perrito55"
}