### LISTAR LOS CONTROLES
GET https://sgpcb-production.up.railway.app/api/v1/controles/0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY4MTMzMDA5MX0.ahbcI8-3eRH6ZGCerISHw4OkOj9GDCqN7EawGI4JJBo

### INSERTAR O MIGRAR LOS DATOS DE LOS CONTROLES
POST https://sgpcb-production.up.railway.app/api/v1/controles HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY4MTMzMDA5MX0.ahbcI8-3eRH6ZGCerISHw4OkOj9GDCqN7EawGI4JJBo
Content-Type: application/json

{

}