### LISTAR LAS AREA QUE INTERVIENEN EN UN PROCESO  DE UNA EMPRESA
GET http://localhost:5001/api/v1/depentactiv/1 HTTP/1.1

### ELIMINAR UN AREA QUE INTERVIENE EN UN PROCESO DE UNA EMPRESA
DELETE http://localhost:5001/api/v1/depentactiv/2 HTTP/1.1

### INSERTAR AREA QUE INTERVIENE EN UN PROCESO DE UNA EMPRESA 
POST http://localhost:5001/api/v1/depentactiv/ HTTP/1.1 
Content-Type: application/json

{
    "id_depActiv" : 1,
    "id_activProc": 1
}