### LISTAR UNA EMPRESA
GET http://localhost:5001/api/v1/empresa/0 HTTP/1.1

### LISTAR UNA ANALISTA EMPRESA
GET https://sgpcb-production.up.railway.app/api/v1/empresa/enlace/5 HTTP/1.1
Authorization: 'Banner eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY4MTAxNjUzMn0.skWhxxYNQ4awHWw4kPp6WTsqvImO3bKa-F4w_rKwjhU'

### ELIMINAR UNA EMPRESA
DELETE http://localhost:5001/api/v1/empresa/1/1 HTTP/1.1

### INSERTAR UNA EMPRESA
POST http://localhost:5001/api/v1/empresa/ HTTP/1.1 
Content-Type: application/json

{
    "id_clienAnalit" : 1,
    "nombreempresa": "Canvaritech",
    "ruc" :  "745465465879",
    "telefono": "985796307",
    "descripc" : "Empresa de entretenimiento y apremdisaje para niños.",
    "rubroempresa" : "Entretenimiento y  Cursos en linea",
    "misio": "Ser una empresa que brinda entretenimiento y aprendisaje a niños, basados en tecnicas de gamificacion, con el fin de que los niños puedan aprender y entretenerce en sus tiempos de ocio, dado desde un entorno virtual, como precencial desde la cede de piura.",
    "vision": "Ser unas de las empresas mas prestigiosas sobre el entretenimiento y aprendisaje en el año 2023."
}

### INSERTAR UNA EMPRESA POR ENLACE ( A - C )
POST http://localhost:5001/api/v1/empresa/enlace HTTP/1.1 
Content-Type: application/json

{
    "id_clienAnalit" : 1,
    "id_empresa" : 1,
    "permis": "C"
}

### ACTUALIZAR UNA EMPRESA
PUT http://localhost:5001/api/v1/empresa/1 HTTP/1.1 
Content-Type: application/json

{
    "nombreempresa": "Lo nuestro Productos Rejionales",
    "ruc" :  "745465465879",
    "telefono": "985796307",
    "descripc" : "Empresa de entretenimiento y apremdisaje para niños.",
    "rubroempresa" : "Entretenimiento y  Cursos en linea",
    "misio": "Somos la mejor empresa que aya existido",
    "vision": "Ser unas de las empresas mas prestigiosas sobre el entretenimiento y aprendisaje en el año 2023."
}