### LISTAR LAS AREAS DE UNA EMPRESA
GET http://localhost:5001/api/v1/objEmpresa/1 HTTP/1.1

### ELIMINAR UN AREA DE UNA EMPRESA
DELETE http://localhost:5001/api/v1/areempr/2 HTTP/1.1

### INSERTAR UN AREA DE UNA EMPRESA EMPRESA
POST http://localhost:5001/api/v1/objEmpresa/ HTTP/1.1 
Content-Type: application/json

{
    "id_empresa" : 1,
    "nombreObje": "Ser una de las empresas del mundo"
}

### ACTUALIZAR UN AREA DE UNA EMPRESA
PUT http://localhost:5001/api/v1/objEmpresa/1 HTTP/1.1 
Content-Type: application/json

{
    "nombrearea": "Administracion",
    "descriparea" :  "Encargado de verlar por todas las areas de la empresa."
}