### LISTAR LA INFORMACION DE UN PROCESO CON RESPECTO A LOS RESPONSABLES, ANALISS, ACTIVOS, AREAS QUE INTERACTUAN
GET http://localhost:5001/api/v1/planesconting/inforproces/8 HTTP/1.1
Authorization: Banner eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5NjkyODAyNTUsIm5vbWJyZSI6ImJyYWRjYXIiLCJlbWFpbCI6InVjdjIwMjFAZW1haWwuY29tIn0sImlhdCI6MTY4MTAxNjUzMn0.skWhxxYNQ4awHWw4kPp6WTsqvImO3bKa-F4w_rKwjhU

### LISTAR LOS ACTIVOS DE UNA EMPRESA
GET http://localhost:5001/api/v1/planesconting/inforamenaz/37/20 HTTP/1.1
