### INSERGAR UN LOG DE LOGEO
POST http://localhost:5001/api/v1/usuar/loginUser HTTP/1.1
Content-Type: application/json

{
    "user": "@pedrna15",
    "pass": "perrito59"
}

### Recuperar la contraseña
# POST http://localhost:5000/usuar/comprespass HTTP/1.1
# Content-Type: application/json

# {
#     "correo": "Arturo14212000@gmail.com"
# }

### RETORNAR KEY API
POST http://localhost:5001/api/v1/usuar/keyApiSession HTTP/1.1
Content-Type: application/json

{
    "seccionkey" : "8fce5e9d-713a-432e-82c4-71c21da174ed"
}

### RETORNAR DATA
POST http://localhost:5001/api/v1/usuar/compDatalog HTTP/1.1
Content-Type: application/json

{
    "seccionkey" : "8fce5e9d-713a-432e-82c4-71c21da174ed"
}