### LEER LA VALORIZACION DE UN ACTIVO
GET http://localhost:5001/api/v1/valorActiv/read/1 HTTP/1.1

### APERTURA LA VALORIZACION DE UN ACTIVO PARA SU EDICION
POST http://localhost:5001/api/v1/valorActiv/ HTTP/1.1 
Content-Type: application/json

{
    "id_activProsVerAnali" : 1,
    "valorActivCuanti": 0
}

### ACTUALIZAR LA VALORIZACION DE UN ACTIVO
PUT http://localhost:5001/api/v1/valorActiv/1 HTTP/1.1 
Content-Type: application/json

{
    "valorActivCuanti" : 1000
}