const express = require('express')
const rooutes = express.Router()
/// ------------------------------------------------------------------------------ callbacks/ triggers
// const skgenerick = require('./sockets/generic.socket')
// const skusuario = require('./sockets/usuarios.socket')
// const sktipocurso = require('./sockets/tipocurso.socket')
/// ------------------------------------------------------------------------------ rotas de app
const verifyToken = require('../config/tockenizer/tokenizer')
const tokeniser = require('../config/tockenizer/router/routertoken')
// const generico = require('./routes/generic.router')
// const messecontac = require('./routes/messecontac.router')
// const admin = require('./routes/admin.router')
// const profes = require('./routes/profesor.router')
const etl = require('./routes/v2/etl.router')
const usuario = require('./routes/v2/usuarios.router')
const clientAnalit = require('./routes/v2/clienteAnalist.router')
const empresa = require('./routes/v2/empresa.router')
const areaEmpresa = require('./routes/v2/areasEmpresa.router')
const objEmpresa = require('./routes/v2/objEmpresa.router')
const trabEmpresa = require('./routes/v2/trabajEmpresa.router')
const gerarproc = require('./routes/v2/gerarproc.router')
const tipProce = require('./routes/v2/tipProce.router')
const proceEmpresa = require('./routes/v2/procesoEmpresa.router')
const resposproce = require('./routes/v2/resposproce.router')
const areainterproce = require('./routes/v2/areainterproce.router')
const tipoActivo = require('./routes/v2/tipoActivo.router')
const activos = require('./routes/v2/activos.router')
const depenActivArbol = require('./routes/v2/depenActivArbol.router')
const activproc = require('./routes/v2/activproces.router')
const escalarto = require('./routes/v2/escalarto.router')
const escalarpo = require('./routes/v2/escalarpo.router')
const valorproces = require('./routes/v2/valorproces.router')
const depentactiv = require('./routes/v2/depentactiv.router')
const versionanali = require('./routes/v2/versionanali.router')
const rolrespon = require('./routes/v2/rolrespon.router')
const responanalis = require('./routes/v2/responanalis.router')
const objVersioAnalis = require('./routes/v2/objVersioAnalis.router')
const dimensioen = require('./routes/v2/dimensioen.router')
const tipocritervalor = require('./routes/v2/tipocritervalor.router')
const nivelvalor = require('./routes/v2/nivelvalor.router')
const criteriosValori = require('./routes/v2/criteriosValori.router')
const valorActiv = require('./routes/v2/valorActiv.router')
const valorActivDim = require('./routes/v2/valorActivDim.router')
const tipoAmenas = require('./routes/v2/tipoAmenas.router')
const amenasas = require('./routes/v2/amenasas.router')
const afectaTip = require('./routes/v2/afectaTip.router')
const afectaDimem = require('./routes/v2/afectaDimem.router')
const escalDegrad = require('./routes/v2/escalDegrad.router')
const escalFrecuen = require('./routes/v2/escalFrecuen.router')
const escalImpact = require('./routes/v2/escalImpact.router')
const escalRiesgo = require('./routes/v2/escalRiesgo.router')
const activprosveranali = require('./routes/v2/activprosveranali.router')
const afectaactiv = require('./routes/v2/afectaactiv.router')
const valorafectamen = require('./routes/v2/valorafectamen.router')
const valorafectamenDim = require('./routes/v2/valorafectamenDim.router')
const tipoSalvaguarda = require('./routes/v2/tipoSalvaguarda.router')
const salvaguardas = require('./routes/v2/salvaguardas.router')
const controles = require('./routes/v2/controles.router')
const classcontroles = require('./routes/v2/classcontroles.router')
const salvafectact = require('./routes/v2/salvafectact.router')
const passalvafect = require('./routes/v2/passalvafect.router')
const responSalvAfectAct = require('./routes/v2/responSalvAfectAct.router')
const recurSalvAfectAct = require('./routes/v2/recurSalvAfectAct.router')
const escalEficacia = require('./routes/v2/escalEficacia.router')
const valorSalvAfectAct = require('./routes/v2/valorSalvAfectAct.router')
const escalImpactResid = require('./routes/v2/escalImpactResid.router')
const escalFrecueResid = require('./routes/v2/escalFrecueResid.router')
const escalDegraResid = require('./routes/v2/escalDegraResid.router')
const escalRiesgResid = require('./routes/v2/escalRiesgResid.router')

// const alumno = require('./routes/alumno.router')
// const tutalum = require('./routes/tutAlum.router')
// const tipocurso = require('./routes/tipocurso.router')
// const sesion = require('./routes/sesion.router')
// const curso = require('./routes/curso.router')
// const ciclocurso = require('./routes/ciclocurso.router')
// const inscrip = require('./routes/inscripccion.router')
// const contsesin = require('./routes/contsesion.router')
// const contactv = require('./routes/contactiv.router')
// const tipocontses = require('./routes/tipcontsesion.router')
// const tareainscr = require('./routes/tareainscr.router')
// const asistenc = require('./routes/asistencia.router')
// const analitic = require('./routes/analiticas.router')
// const pointclass = require('./routes/puntosclass.router')
// const insertpuntclas = require('./routes/inscrpointclas.router')
// ftp midelware
const ftpgoogle = require('../config/ftp/googledrive/cloudgoogle')
const ftpclodyn = require('../config/ftp/cloudinary/uploudcloud')

// --------------------------------------------------------------------------------- ROUTER EXPRESS
// api de tokenizer
rooutes.use('/tokeniser', tokeniser)
// --------------------------------------------------------------------------------- ejecucion de router
// rooutes.use('/messecontac', messecontac)
rooutes.use('/etl', etl)
rooutes.use('/usuar', usuario)
rooutes.use('/clientAnalit', clientAnalit)
rooutes.use('/empresa', empresa)
rooutes.use('/areempr', areaEmpresa)
rooutes.use('/objEmpresa', objEmpresa)
rooutes.use('/gerarproc', gerarproc)
rooutes.use('/tipProce', tipProce)
rooutes.use('/trabEmpresa', trabEmpresa)
rooutes.use('/proceEmpresa', proceEmpresa)
rooutes.use('/resposproce', resposproce)
rooutes.use('/areainterproce', areainterproce)
rooutes.use('/tipoActivo', tipoActivo)
rooutes.use('/activos', activos)
rooutes.use('/activproc', activproc)
rooutes.use('/escalarto', escalarto)
rooutes.use('/escalarpo', escalarpo)
rooutes.use('/valorproces', valorproces)
rooutes.use('/depentactiv', depentactiv)
rooutes.use('/versionanali', versionanali)
rooutes.use('/depenActivArbol', depenActivArbol)
rooutes.use('/rolrespon', rolrespon)
rooutes.use('/responanalis', responanalis)
rooutes.use('/objVersioAnalis', objVersioAnalis)
rooutes.use('/dimensioen', dimensioen)
rooutes.use('/tipocritervalor', tipocritervalor)
rooutes.use('/nivelvalor', nivelvalor)
rooutes.use('/criteriosValori', criteriosValori)
rooutes.use('/valorActiv', valorActiv)
rooutes.use('/valorActivDim', valorActivDim)
rooutes.use('/tipoAmenas', tipoAmenas)
rooutes.use('/amenasas', amenasas)
rooutes.use('/afectaTip', afectaTip)
rooutes.use('/afectaDimem', afectaDimem)
rooutes.use('/escalDegrad', escalDegrad)
rooutes.use('/escalFrecuen', escalFrecuen)
rooutes.use('/escalImpact', escalImpact)
rooutes.use('/escalRiesgo', escalRiesgo)
rooutes.use('/activprosveranali', activprosveranali)
rooutes.use('/afectaactiv', afectaactiv)
rooutes.use('/valorafectamen', valorafectamen)
rooutes.use('/valorafectamenDim', valorafectamenDim)
rooutes.use('/tipoSalvaguarda', tipoSalvaguarda)
rooutes.use('/salvaguardas', salvaguardas)
rooutes.use('/controles', controles)
rooutes.use('/classcontroles', classcontroles)
rooutes.use('/salvafectact', salvafectact)
rooutes.use('/passalvafect', passalvafect)
rooutes.use('/responSalvAfectAct', responSalvAfectAct)
rooutes.use('/recurSalvAfectAct', recurSalvAfectAct)
rooutes.use('/escalEficacia', escalEficacia)
rooutes.use('/valorSalvAfectAct', valorSalvAfectAct)
rooutes.use('/escalImpactResid', escalImpactResid)
rooutes.use('/escalFrecueResid', escalFrecueResid)
rooutes.use('/escalDegraResid', escalDegraResid)
rooutes.use('/escalRiesgResid', escalRiesgResid)

// rooutes.use('/admi', verifyToken, admin)
// rooutes.use('/profe', verifyToken, profes)
// rooutes.use('/alumn', alumno)
// rooutes.use('/tutalm', tutalum)
// rooutes.use('/tipocur', verifyToken, tipocurso)
// rooutes.use('/sesion', sesion)
// rooutes.use('/curso', verifyToken, curso)
// rooutes.use('/cicurs', ciclocurso)
// rooutes.use('/inscri', verifyToken, inscrip)
// rooutes.use('/contses', verifyToken, contsesin)
// rooutes.use('/contactv', verifyToken, contactv)
// rooutes.use('/tipcontses', verifyToken, tipocontses)
// rooutes.use('/tarinsc', verifyToken, tareainscr)
// rooutes.use('/asisten', verifyToken, asistenc)
// rooutes.use('/anli', verifyToken, analitic)
// rooutes.use('/pointcl', verifyToken, pointclass)
// rooutes.use('/inspuntclas', verifyToken, insertpuntclas)
// router ftp
rooutes.use('/ftpgoogle', ftpgoogle) // subir archivos
rooutes.use('/ftpclodyn', ftpclodyn) // subir archivos

// --------------------------------------------------------------------------------- SOCKET IO
// const SocketIo = (socket) => {
//   skgenerick(socket)
//   skusuario(socket)
//   sktipocurso(socket)
// }

module.exports = {
  rooutes
  // ,SocketIo
}
