const express = require('express')
const rooutes = express.Router()
/// ------------------------------------------------------------------------------ callbacks/ triggers
// const skgenerick = require('./sockets/generic.socket')
// const skusuario = require('./sockets/usuarios.socket')
// const sktipocurso = require('./sockets/tipocurso.socket')
/// ------------------------------------------------------------------------------ rotas de app
const verifyToken = require('../config/tockenizer/tokenizer')
const tokeniser = require('../config/tockenizer/router/routertoken')
// const generico = require('./routes/generic.router')
// const messecontac = require('./routes/messecontac.router')
// const admin = require('./routes/admin.router')
// const profes = require('./routes/profesor.router')
const etl = require('./routes/v2/etl.router')
const usuario = require('./routes/v2/usuarios.router')
const clientAnalit = require('./routes/v2/clienteAnalist.router')
const empresa = require('./routes/v2/empresa.router')
const areaEmpresa = require('./routes/v2/areasEmpresa.router')
const objEmpresa = require('./routes/v2/objEmpresa.router')
const trabEmpresa = require('./routes/v2/trabajEmpresa.router')
const gerarproc = require('./routes/v2/gerarproc.router')
const tipProce = require('./routes/v2/tipProce.router')
const proceEmpresa = require('./routes/v2/procesoEmpresa.router')
const resposproce = require('./routes/v2/resposproce.router')
const areainterproce = require('./routes/v2/areainterproce.router')
const tipoActivo = require('./routes/v2/tipoActivo.router')
const activos = require('./routes/v2/activos.router')
const depenActivArbol = require('./routes/v2/depenActivArbol.router')
const activproc = require('./routes/v2/activproces.router')
const escalarto = require('./routes/v2/escalarto.router')
const escalarpo = require('./routes/v2/escalarpo.router')
const valorproces = require('./routes/v2/valorproces.router')
const depentactiv = require('./routes/v2/depentactiv.router')
const versionanali = require('./routes/v2/versionanali.router')
const rolrespon = require('./routes/v2/rolrespon.router')
const responanalis = require('./routes/v2/responanalis.router')
const objVersioAnalis = require('./routes/v2/objVersioAnalis.router')
const dimensioen = require('./routes/v2/dimensioen.router')
const tipocritervalor = require('./routes/v2/tipocritervalor.router')
const nivelvalor = require('./routes/v2/nivelvalor.router')
const criteriosValori = require('./routes/v2/criteriosValori.router')
const valorActiv = require('./routes/v2/valorActiv.router')
const valorActivDim = require('./routes/v2/valorActivDim.router')
const tipoAmenas = require('./routes/v2/tipoAmenas.router')
const amenasas = require('./routes/v2/amenasas.router')
const afectaTip = require('./routes/v2/afectaTip.router')
const afectaDimem = require('./routes/v2/afectaDimem.router')
const escalDegrad = require('./routes/v2/escalDegrad.router')
const escalFrecuen = require('./routes/v2/escalFrecuen.router')
const escalImpact = require('./routes/v2/escalImpact.router')
const escalRiesgo = require('./routes/v2/escalRiesgo.router')
const activprosveranali = require('./routes/v2/activprosveranali.router')
const afectaactiv = require('./routes/v2/afectaactiv.router')
const valorafectamen = require('./routes/v2/valorafectamen.router')
const valorafectamenDim = require('./routes/v2/valorafectamenDim.router')
const tipoSalvaguarda = require('./routes/v2/tipoSalvaguarda.router')
const salvaguardas = require('./routes/v2/salvaguardas.router')
const controles = require('./routes/v2/controles.router')
const classcontroles = require('./routes/v2/classcontroles.router')
const salvafectact = require('./routes/v2/salvafectact.router')
const passalvafect = require('./routes/v2/passalvafect.router')
const responSalvAfectAct = require('./routes/v2/responSalvAfectAct.router')
const recurSalvAfectAct = require('./routes/v2/recurSalvAfectAct.router')
const escalEficacia = require('./routes/v2/escalEficacia.router')
const valorSalvAfectAct = require('./routes/v2/valorSalvAfectAct.router')
const escalImpactResid = require('./routes/v2/escalImpactResid.router')
const escalFrecueResid = require('./routes/v2/escalFrecueResid.router')
const escalDegraResid = require('./routes/v2/escalDegraResid.router')
const escalRiesgResid = require('./routes/v2/escalRiesgResid.router')
const insidencias = require('./routes/v2/insidencias.router')
const afecactivinsiden = require('./routes/v2/afecactivinsiden.router')
const planesConting = require('./routes/v2/planesConting.router')

// const alumno = require('./routes/alumno.router')
// const tutalum = require('./routes/tutAlum.router')
// const tipocurso = require('./routes/tipocurso.router')
// const sesion = require('./routes/sesion.router')
// const curso = require('./routes/curso.router')
// const ciclocurso = require('./routes/ciclocurso.router')
// const inscrip = require('./routes/inscripccion.router')
// const contsesin = require('./routes/contsesion.router')
// const contactv = require('./routes/contactiv.router')
// const tipocontses = require('./routes/tipcontsesion.router')
// const tareainscr = require('./routes/tareainscr.router')
// const asistenc = require('./routes/asistencia.router')
// const analitic = require('./routes/analiticas.router')
// const pointclass = require('./routes/puntosclass.router')
// const insertpuntclas = require('./routes/inscrpointclas.router')
// ftp midelware
const ftpgoogle = require('../config/ftp/googledrive/cloudgoogle')
const ftpclodyn = require('../config/ftp/cloudinary/uploudcloud')

// --------------------------------------------------------------------------------- ROUTER EXPRESS
// api de tokenizer
rooutes.use('/tokeniser', tokeniser)
// --------------------------------------------------------------------------------- ejecucion de router
// rooutes.use('/messecontac', messecontac)
rooutes.use('/etl', etl)
rooutes.use('/usuar', usuario)
rooutes.use('/clientAnalit', clientAnalit)
rooutes.use('/empresa', verifyToken, empresa)
rooutes.use('/areempr', verifyToken, areaEmpresa)
rooutes.use('/objEmpresa', verifyToken, objEmpresa)
rooutes.use('/gerarproc', verifyToken, gerarproc)
rooutes.use('/tipProce', verifyToken, tipProce)
rooutes.use('/trabEmpresa', verifyToken, trabEmpresa)
rooutes.use('/proceEmpresa', verifyToken, proceEmpresa)
rooutes.use('/resposproce', verifyToken, resposproce)
rooutes.use('/areainterproce', verifyToken, areainterproce)
rooutes.use('/tipoActivo', verifyToken, tipoActivo)
rooutes.use('/activos', verifyToken, activos)
rooutes.use('/activproc', verifyToken, activproc)
rooutes.use('/escalarto', verifyToken, escalarto)
rooutes.use('/escalarpo', verifyToken, escalarpo)
rooutes.use('/valorproces', verifyToken, valorproces)
rooutes.use('/depentactiv', verifyToken, depentactiv)
rooutes.use('/versionanali', verifyToken, versionanali)
rooutes.use('/depenActivArbol', depenActivArbol)
rooutes.use('/rolrespon', verifyToken, rolrespon)
rooutes.use('/responanalis', verifyToken, responanalis)
rooutes.use('/objVersioAnalis', verifyToken, objVersioAnalis)
rooutes.use('/dimensioen', verifyToken, dimensioen)
rooutes.use('/tipocritervalor', verifyToken, tipocritervalor)
rooutes.use('/nivelvalor', verifyToken, nivelvalor)
rooutes.use('/criteriosValori', verifyToken, criteriosValori)
rooutes.use('/valorActiv', verifyToken, valorActiv)
rooutes.use('/valorActivDim', verifyToken, valorActivDim)
rooutes.use('/tipoAmenas', verifyToken, tipoAmenas)
rooutes.use('/amenasas', verifyToken, amenasas)
rooutes.use('/afectaTip', verifyToken, afectaTip)
rooutes.use('/afectaDimem', verifyToken, afectaDimem)
rooutes.use('/escalDegrad', verifyToken, escalDegrad)
rooutes.use('/escalFrecuen', verifyToken, escalFrecuen)
rooutes.use('/escalImpact', verifyToken, escalImpact)
rooutes.use('/escalRiesgo', verifyToken, escalRiesgo)
rooutes.use('/activprosveranali', verifyToken, activprosveranali)
rooutes.use('/afectaactiv', verifyToken, afectaactiv)
rooutes.use('/valorafectamen', verifyToken, valorafectamen)
rooutes.use('/valorafectamenDim', verifyToken, valorafectamenDim)
rooutes.use('/tipoSalvaguarda', verifyToken, tipoSalvaguarda)
rooutes.use('/salvaguardas', verifyToken, salvaguardas)
rooutes.use('/controles', verifyToken, controles)
rooutes.use('/classcontroles', verifyToken, classcontroles)
rooutes.use('/salvafectact', verifyToken, salvafectact)
rooutes.use('/passalvafect', verifyToken, passalvafect)
rooutes.use('/responSalvAfectAct', verifyToken, responSalvAfectAct)
rooutes.use('/recurSalvAfectAct', verifyToken, recurSalvAfectAct)
rooutes.use('/escalEficacia', verifyToken, escalEficacia)
rooutes.use('/valorSalvAfectAct', verifyToken, valorSalvAfectAct)
rooutes.use('/escalImpactResid', verifyToken, escalImpactResid)
rooutes.use('/escalFrecueResid', verifyToken, escalFrecueResid)
rooutes.use('/escalDegraResid', verifyToken, escalDegraResid)
rooutes.use('/escalRiesgResid', verifyToken, escalRiesgResid)
rooutes.use('/insidencias', verifyToken, insidencias)
rooutes.use('/afecactivinsiden', verifyToken, afecactivinsiden)
rooutes.use('/planesconting', verifyToken, planesConting)

// rooutes.use('/admi', verifyToken, admin)
// rooutes.use('/profe', verifyToken, profes)
// rooutes.use('/alumn', alumno)
// rooutes.use('/tutalm', tutalum)
// rooutes.use('/tipocur', verifyToken, tipocurso)
// rooutes.use('/sesion', sesion)
// rooutes.use('/curso', verifyToken, curso)
// rooutes.use('/cicurs', ciclocurso)
// rooutes.use('/inscri', verifyToken, inscrip)
// rooutes.use('/contses', verifyToken, contsesin)
// rooutes.use('/contactv', verifyToken, contactv)
// rooutes.use('/tipcontses', verifyToken, tipocontses)
// rooutes.use('/tarinsc', verifyToken, tareainscr)
// rooutes.use('/asisten', verifyToken, asistenc)
// rooutes.use('/anli', verifyToken, analitic)
// rooutes.use('/pointcl', verifyToken, pointclass)
// rooutes.use('/inspuntclas', verifyToken, insertpuntclas)
// router ftp
rooutes.use('/ftpgoogle', ftpgoogle) // subir archivos
rooutes.use('/ftpclodyn', ftpclodyn) // subir archivos

// --------------------------------------------------------------------------------- SOCKET IO
// const SocketIo = (socket) => {
//   skgenerick(socket)
//   skusuario(socket)
//   sktipocurso(socket)
// }

module.exports = {
  rooutes
  // ,SocketIo
}
